---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by msn.
--- DateTime: 2021/4/21 20:55
---
---//这是一个虚表
local a = {test2=2,__index={test2=9527} ,cas=function()  print("safsafjasokfhasf") end}
local b= {}
b.test=1

local c ={}
setmetatable(c,{__index = b[a]})
print(c.test2);



